# Generated by Django 3.2.8 on 2021-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='extension',
            field=models.CharField(default='', max_length=10, verbose_name='extension'),
            preserve_default=False,
        ),
    ]
