# Generated by Django 3.2.8 on 2021-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='value'),
        ),
    ]
